jobs:
  remove_backport_branch:
    if: startsWith(github.event.pull_request.head.ref, 'bp-')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Delete PR head branches
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        numbers: ${{github.event.pull_request.number}}
name: Backport branch reaper
on:
  repository_dispatch:
    types: trigger-ga___backport_reaper.yaml
