jobs:
  createJira:
    if: github.actor == 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name,
      'github_actions') && startsWith(github.event.pull_request.title, 'Bump')
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Jira Summary
      run: echo SUMMARY=$(echo "${{ github.event.pull_request.title }}" | grep -oP
        '(?<=Bump )(.*)(?=from)|(?<=to )(.*)' | tr -d '\n') >> $GITHUB_ENV
    - continue-on-error: true
      env:
        ASSIGNEE: infinispan-bot
        PROJECT_KEY: ISPN
        PULL_REQUEST: ${{ github.event.pull_request.html_url }}
        RUNNER_DEBUG: '1'
        SUMMARY: ${{ env.SUMMARY }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        TYPE: Component Upgrade
      name: Create or Update Existing Jira
      run: 'source ./bin/jira/upsert.sh

        echo "JIRA_ISSUE_KEY=${JIRA_ISSUE_KEY}" >> $GITHUB_ENV

        echo "JIRA_ISSUE_URL=${JIRA_ISSUE_URL}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Add comment to PR
      run: gh pr comment ${{ github.event.pull_request.number }} --body ${{ env.JIRA_ISSUE_URL
        }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.base_ref == 'main' }}
      name: Update PR Title main
      run: gh pr edit ${{ github.event.pull_request.number }} --title "${{ env.JIRA_ISSUE_KEY
        }} ${{ github.event.pull_request.title }}"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.base_ref == '14.0.x' }}
      name: Update PR Title 14.0.x
      run: gh pr edit ${{ github.event.pull_request.number }} --title "[14.0.x] ${{
        env.JIRA_ISSUE_KEY }} ${{ github.event.pull_request.title }}"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_KEY: ISPN
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      id: milestone
      name: Set PR Milestone
      run: 'sudo apt-get install xmlstarlet

        MVN_VERSION=$(xmlstarlet sel -t -m _:project -v _:version pom.xml)

        export MAJOR_VERSION=${MVN_VERSION%.*.*}

        gh pr edit ${{ github.event.pull_request.number }} --milestone "$(./bin/jira/get_milestone.sh)"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      name: Approve PR for auto-merge
      run: gh pr merge --auto --rebase ${{ github.event.pull_request.number }}
name: Dependabot Jira
on:
  repository_dispatch:
    types: trigger-ga___dependabot_pull_request.yml
