jobs:
  triage:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: eps1lon/actions-label-merge-conflict@releases/2.x
      with:
        dirtyLabel: Needs Rebase
        repoToken: ${{ secrets.GITHUB_TOKEN }}
name: Needs Rebase Check
on:
  repository_dispatch:
    types: trigger-ga___needs_rebase.yaml
