jobs:
  image:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        repository: infinispan/infinispan-images
    - continue-on-error: true
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        repository: infinispan/infinispan-images
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        path: server
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build Infinispan
      run: './mvnw -s maven-settings.xml install -DskipTests -am -pl server/runtime

        SERVER_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args=''${project.version}''
        --non-recursive exec:exec)

        cd server/runtime/target

        zip -r ${GITHUB_WORKSPACE}/server.zip infinispan-server-${SERVER_VERSION}

        '
      working-directory: server
    - continue-on-error: true
      name: Install CEKit
      uses: cekit/actions-setup-cekit@v1.1.5
    - continue-on-error: true
      name: Create Dockerfile
      run: 'SERVER_OVERRIDE="{\"artifacts\":[{\"name\":\"server\",\"path\":\"${GITHUB_WORKSPACE}/server.zip\"}]}"

        cekit -v --descriptor server-openjdk.yaml build --overrides ''{''version'':
        ''${{ github.sha }}''}'' --overrides ${SERVER_OVERRIDE} --dry-run docker

        '
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Build Image
      run: 'cat target/image/Dockerfile

        docker buildx build --load -t localhost:5001/server:${{ github.sha }} target/image

        docker save localhost:5001/server:${{ github.sha }} > /tmp/operand-image.tar

        '
    - continue-on-error: true
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: operand-image
        path: /tmp/operand-image.tar
  tests:
    needs: image
    uses: infinispan/infinispan-operator/.github/workflows/upgrade_tests.yaml@main
    with:
      operand: localhost:5001/server:${{ github.sha }}
      operandArtifact: operand-image
      ref: main
      repository: infinispan/infinispan-operator
name: Operator Upgrade Tests
on:
  repository_dispatch:
    types: trigger-ga___operator_upgrade.yaml
