jobs:
  updateJira:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      name: Extract Jira Key
      run: echo ISSUE_KEY=$(echo "${PR_TITLE}" | grep -oP 'ISPN-(?P<id>[0-9]+)') >>
        $GITHUB_ENV
    - continue-on-error: true
      env:
        ISSUE_KEY: ${{ env.ISSUE_KEY }}
        PULL_REQUEST: ${{ github.event.pull_request.html_url }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      if: ${{ env.ISSUE_KEY != '' }}
      name: Link Pull Request
      run: ./bin/jira/add_pull_request.sh
    - continue-on-error: true
      env:
        ISSUE_KEY: ${{ env.ISSUE_KEY }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        VERSION: ${{ github.event.pull_request.milestone.title }}
      if: ${{ env.ISSUE_KEY != '' }}
      name: Add Fix Version
      run: ./bin/jira/add_fix_version.sh
    - continue-on-error: true
      env:
        ISSUE_KEY: ${{ env.ISSUE_KEY }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        TRANSITION: Resolved
      if: ${{ env.ISSUE_KEY != '' }} && !contains(github.event.pull_request.labels.*.name,
        '14.0.x')
      name: Transition Issue to Resolved
      run: ./bin/jira/transition.sh
name: Pull Request Merged
on:
  repository_dispatch:
    types: trigger-ga___pull_request_merged.yml
