jobs:
  updateJira:
    if: github.actor != 'dependabot[bot]'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      name: Extract Jira Key
      run: echo ISSUE_KEY=$(echo "${PR_TITLE}" | grep -oP 'ISPN-(?P<id>[0-9]+)') >>
        $GITHUB_ENV
    - continue-on-error: true
      run: echo ${{ env.ISSUE_KEY }}
    - continue-on-error: true
      run: echo "$ISSUE_KEY"
    - continue-on-error: true
      env:
        ISSUE_KEY: ${{ env.ISSUE_KEY }}
        PULL_REQUEST: ${{ github.event.pull_request.html_url }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      if: ${{ env.ISSUE_KEY != '' }}
      name: Link Pull Request
      run: ./bin/jira/add_pull_request.sh
    - continue-on-error: true
      env:
        ISSUE_KEY: ${{ env.ISSUE_KEY }}
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        TRANSITION: Code Review
      if: ${{ env.ISSUE_KEY != '' }}
      name: Transition Issue to Code Review
      run: ./bin/jira/transition.sh
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_KEY: ISPN
        TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      id: milestone
      name: Set PR Milestone
      run: 'sudo apt-get install xmlstarlet

        MVN_VERSION=$(xmlstarlet sel -t -m _:project -v _:version pom.xml)

        export MAJOR_VERSION=${MVN_VERSION%.*.*}

        gh pr edit ${{ github.event.pull_request.number }} --milestone "$(./bin/jira/get_milestone.sh)"

        '
name: Pull Request Open
on:
  repository_dispatch:
    types: trigger-ga___pull_request_open.yml
