jobs:
  native-cli:
    needs: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-2022' }}
      name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: graalvm
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '21'
    - continue-on-error: true
      name: Checkout Release Tag
      uses: actions/checkout@v4
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-2022' }}
      name: Build native executable
      run: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        x86_amd64

        mvnw.cmd package -s maven-settings.xml -Pdistribution -Pwindows -Pnative -am
        -pl quarkus/cli

        '
      shell: cmd
    - continue-on-error: true
      if: ${{ matrix.os != 'windows-2022' }}
      name: Build native executable
      run: ./mvnw package -s maven-settings.xml -Pdistribution -Pnative -am -pl quarkus/cli
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-cli-native-executable
      name: Upload CLI native executable
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/zip
        asset_name: infinispan-cli-${{github.ref_name}}-${{ matrix.asset_name }}.zip
        asset_path: ./quarkus/cli/target/infinispan-cli-${{github.ref_name}}.zip
        upload_url: ${{ needs.release.outputs.upload_url }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - asset_name: linux-amd64
          gu_binary: gu
          os: ubuntu-latest
        - asset_name: darwin-amd64
          gu_binary: gu
          os: macos-latest
        - asset_name: windows-amd64
          gu_binary: gu.cmd
          os: windows-2022
        os:
        - ubuntu-latest
        - macos-latest
        - windows-2022
  release:
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Source
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: release
      name: Create Release
      uses: actions/create-release@v1
      with:
        prerelease: ${{ !contains(github.ref_name, '.Final') }}
        release_name: ${{github.ref_name}}
        tag_name: ${{github.ref_name}}
  server-upload:
    needs: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Server
      run: wget https://downloads.jboss.org/infinispan/${{github.ref_name}}/infinispan-server-${{github.ref_name}}.zip
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload Server to Release
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/zip
        asset_name: infinispan-server-${{github.ref_name}}.zip
        asset_path: infinispan-server-${{github.ref_name}}.zip
        upload_url: ${{ needs.release.outputs.upload_url }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
