jobs:
  upload:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Maven
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: 17
        maven-version: 3.9.0
    - continue-on-error: true
      name: Build docs with Maven
      run: mvn install -Pdistribution -pl documentation -am -s maven-settings.xml
    - continue-on-error: true
      name: Clone infinispan.github.io
      uses: actions/checkout@master
      with:
        path: infinispan.github.io
        ref: master
        repository: infinispan/infinispan.github.io
    - continue-on-error: true
      if: github.ref == 'refs/heads/main'
      name: Copy docs to dev
      run: 'cp -r documentation/target/generated/1*/html/* infinispan.github.io/docs/dev/

        '
    - continue-on-error: true
      if: github.ref == 'refs/heads/14.0.x'
      name: Copy docs to stable
      run: 'cp -r documentation/target/generated/1*/html/* infinispan.github.io/docs/stable/

        '
    - continue-on-error: true
      name: Commit files
      run: 'cd infinispan.github.io

        git config -l | grep ''http\..*\.extraheader'' | cut -d= -f1 | xargs -L1 git
        config --unset-all

        git config --global user.email "infinispan@infinispan.org"

        git config --global user.name "Infinispan"

        git add . --all

        git commit -m "Synchronized core docs from ${{ github.ref }}"

        '
    - continue-on-error: true
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      name: Push to the community site
      uses: cpina/github-action-push-to-another-repository@main
      with:
        destination-github-username: infinispan
        destination-repository-name: infinispan.github.io
        source-directory: infinispan.github.io
        target-branch: master
        user-email: infinispan@infinispan.org
name: Synchronize changes to the website
on:
  repository_dispatch:
    types: trigger-ga___sync_docs.yml
permissions:
  contents: read
